version: 2
updates:
  - package-ecosystem: npm
    directory: "web-ui"
    schedule:
      interval: daily
    open-pull-requests-limit: 30
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 30
    labels:
      - automerge
      - dependencies
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 30
    ignore:
      - dependency-name: "github.com/cosmos/cosmos-sdk"
    labels:
      - automerge
      - dependencies
